[project]
name = "at-splink-ersl-two"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sekhar talupula", email = "sekher.talupula@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pytest==7.1.3"
]

[project.scripts]
at-splink-ersl-two = "at_splink_ersl_two:main"
#prn = "at_splink_ersl_two.packages.person.src.person.pone:main"




[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "packages/commons",
    "packages/person",
    "packages/organization",
]


[tool.pytest.ini_options]
pythonpath = ["."]

